### PR TITLE
Adding information about factions to Factions and Galactic Map

### PR DESCRIPTION
**Pull request by EricWarnke**
Made info.json readable by formatting the JSON. It's unusable in flattened format.

I added information on Factions as requested in this thread: https://www.reddit.com/r/NoMansSkyTheGame/comments/4i0e7w/suggested_update_for_nms_info_repository_factions/

### CODE REVIEW

**Comment by EricWarnke** [comment]
I realize now that reformatting makes my changes impossible to read. If you want them to be separate commits let me know.

**Comment by s-thom** [comment]
I kept the JSON flat so that it wouldn't take up 1000 lines (not exaggerating either). Just copy a single line, put into the generator, make changes, copy from generator (which is flat, thanks to `JSON.stringify()`), paste straight back in. It does make diffs a little unreadable through.

Speaking of diffs, could you add your changes to `recent.json`, as there isn't an automatic process of doing that.

**Comment by EricWarnke** [comment]
Ok, done.

I don't agree with the methodology, because my opinion is 1000 lines of easy to read JSON is better than requiring a generator. But it's your project, so kudos on everything you've done so far!

**Comment by s-thom** [comment]
The generator was for those who haven't done anything code/data structure related and just wanted to contribute to the repository. 

Thanks, and I've merged your changes.

**Pull request merged**
